### ISSUE TITLE
Some problems...

### ISSUE THREAD

**Issue by szerntt** [Dhiiyaur/mangamee#1]
When you log in, home screen get completely blank.
..
in chapter page doesn't have next-prev chapter.
..
images are too big, they are get worse.
..
It would be nice if the manga section was a chapter search box

thanks..

**Comment by Dhiiyaur** [comment]
Done...

**Comment by szerntt** [comment]
And it's would be good if in chapter field has a search bar for long mangas.
[like this](https://s3.imgbu.com/file/imgbucom-s/2021/03/04/Screenshot-2021-03-04-13375387879eed54587c59.png)

**Comment by Dhiiyaur** [comment]
Alright, done bro..

**Comment by szerntt** [comment]
well i will keep you busy again 😄 
When i search a chapter, chapter name get listed but when i click the chapter i search not opened, the original chapter get opened.

[my first step](https://s3.imgbu.com/file/imgbucom-s/2021/03/04/gone47f6fd48d86db18e.png)
[opened chapter](https://s3.imgbu.com/file/imgbucom-s/2021/03/04/gtwoe695a76934e52385.png)
[original place](https://ibb.co/N3vSrXG)

**Comment by Dhiiyaur** [comment]
ah.. my mistake, done...

**Comment by szerntt** [comment]
In signup page, when write wrong passwords in two input its says 'passwords dont math' but still going to login panel

**Comment by Dhiiyaur** [comment]
done, fix bug sign up, for add some features, maybe later

**Comment by szerntt** [comment]
👍
